export const adminArray: IStaff[] = [
	{
		id: '1',
		name: 'Агибалов Александр Владимирович',
		post: 'Ректор Воронежского ГАУ',
		photo: '',
		cabinet: '101',
		tel: '253-86-31',
		email: 'main@vsau.ru',
	},
	{
		id: '1',
		name: 'Агибалов Александр Владимирович',
		post: 'Ректор Воронежского ГАУ',
		photo: '',
		cabinet: '101',
		tel: '253-86-31',
		email: 'main@vsau.ru',
	},
	{
		id: '1',
		name: 'Агибалов Александр Владимирович',
		post: 'Ректор Воронежского ГАУ',
		photo: '',
		cabinet: '101',
		tel: '253-86-31',
		email: 'main@vsau.ru',
	},
	{
		id: '1',
		name: 'Агибалов Александр Владимирович',
		post: 'Ректор Воронежского ГАУ',
		photo: '',
		cabinet: '101',
		tel: '253-86-31',
		email: 'main@vsau.ru',
	},
]
