name: CI/CD

on:
  # Build + Deploy
  push:
    branches:
      - develop

jobs:
  deploy:
    name: 'Build and deploy'
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/key
          chmod 600 ~/.ssh/key
          cat >>~/.ssh/config <<END
          Host qq
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}

      - name: Get frontend repo
        uses: actions/checkout@v3

      - name: Install Node.js v20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Build frontend
        run: |
          npm install sharp && npm cache clean --force
          npm install --save-dev typescript @types/node && npm cache clean --force
          npm install && npm cache clean --force
          npm run build
          rm -r ./node_modules

      - name: Update frontend
        run: |
          rsync -e 'ssh -i ~/.ssh/key -o StrictHostKeyChecking=no' --archive --compress --delete . ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.SSH_WORKDIR }}

      - name: Deploy frontend
        run: ssh qq 'cd ${{ secrets.SSH_WORKDIR }} && cd .. && docker-compose build && docker-compose up -d'
